language: java
env:
  - NODE_VERSION=6.10.2
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta
before_install:
  - cd backend && ./gradlew clean && cd ..
  - cd frontend && nvm install $NODE_VERSION && nvm use $NODE_VERSION && npm install -g yarn && cd ..
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
cache:
  directories:
    - frontend/node_modules
jdk:
  - oraclejdk8
services: mongodb
install:
  - cd frontend && yarn && cd ..
before_script:
  - npm install -g @angular/cli
script: cd backend && ./gradlew test && cd ../frontend && ng test --single-run
notifications:
  email: false