server:
  port: 8080
spring:
  data:
    mongodb:
      database: mockpi
api:
  fakeContextRoot: /mockpi

---

spring:
  profiles: cloud
  data:
    mongodb:
      database: mockpi
      host: dep01-int.documents.azure.com
      port: 10250